---

- name: Install phpipam
  git:
    repo: https://github.com/phpipam/phpipam.git
    dest: "{{ phpipam_installdir }}"
    clone: yes
    update: no
    version: "{{ phpipam_branch }}"
    track_submodules: yes

- name: remove unused files
  file:
    path: "{{ phpipam_installdir }}/{{ item }}"
    state: absent
  with_items:
  - config.docker.php
  - config.dist.php
  - INSTALL.txt
  - README.md
  - UPDATE

...