---

- name: Install phpipam
  git:
    repo: https://github.com/phpipam/phpipam.git
    dest: "{{ phpipam_installdir }}"
    clone: yes
    update: no
    version: "{{ phpipam_branch }}"
    track_submodules: yes

- name: remove unused files
  file:
    path: "{{ phpipam_installdir }}/{{ item }}"
    state: absent
  with_items:
  - config.docker.php
  - config.dist.php
  - INSTALL.txt
  - README.md
  - UPDATE

- name: update cronjobs
  template:
    src: templates/cron_file.j2
    dest: /etc/cron.d/phpipam

- name: fix php bug
  file:
    path: /var/opt/remi/php73/lib/php/session
    group: nginx
    owner: nginx

- name: change owner
  file:
    path: "{{ phpipam_installdir }}"
    owner: nginx
    group: nginx
    recurse: yes
    state: directory

- name: set uploads permission
  file:
    path: "{{ phpipam_installdir }}/app/admin/import-export/upload/"
    owner: nginx
    group: nginx
    state: directory
    mode: '0777'

- name: create auto-exporter dir
  file:
    path:  /opt/phpipam_exporter
    state: directory

- name: setup auto-exporter files
  template:
    src: tempaltes/export_{{ item }}.j2
    dest: /opt/phpipam_exporter/{{ item }}
  with_items:
  - cronjob.sh
  - generate-xls.php

- name: create cronjob for export
  cron:
    name: "phpipam_auto-exporter"
    minute: "15"
    hour: "2"
    job: "/opt/phpipam_exporter/cronjob.sh"
...