---
- name: import include vars tasks
  import_tasks: 'include-vars.yml'
  tags:
  - role_phpipam
  - includes

- name: run dependency
  include_tasks: dependency.yml
  tags:
  - role_phpipam
  - dependency

- name: installation
  include_tasks: install.yml
  tags:
  - role_phpipam

- name: config
  include_tasks: config.yml
  tags:
  - role_phpipam
...
