---
- name: import include vars tasks
  import_tasks: 'include-vars.yml'
  tags:
  - role_phpipam
  - includes

- name: installation
  include_tasks: install.yml
  tags:
  - role_phpipam
  when: duo_install == true

- name: config
  include_tasks: config.yml
  tags:
  - role_phpipam
...
